name: Generate_SBOM # ✅ No dots

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_sbom: # ✅ No dots or special characters
    name: Generate SBOM from source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM using Anchore
        uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom-cyclonedx.json
          dependency-snapshot: true

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx-json
          path: sbom-cyclonedx.json
