name: SBOM.json

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  Anchore-Source-Scan:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Scan source code and upload dependency results
        uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
        with:
          path: .
          dependency-snapshot: true
          format: cyclonedx-json
