name: Generate_SBOM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate_sbom:
    name: Generate and Upload SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM using Anchore
        uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom-cyclonedx.json

      - name: Upload SBOM to Portasecura
        env:
          PORTASECURA_API_URL: https://dependency.portasecura.com/api/v1/bom
          PORTASECURA_API_TOKEN: ${{6333c073-d740-4994-bbdf-7a2998144774}}
        run: |
          curl -X POST "$PORTASECURA_API_URL" \
            -H "Authorization: Bearer $PORTASECURA_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data-binary @sbom-cyclonedx.json
