name: "Secrets"
on:
  push:
    branches-ignore:
      - l10n_develop
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'monitoring/grafana-dashboard.json'
      - 'screenshots/**'
    tags-ignore:
      - '*'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'data/static/i18n/*.json'
      - 'frontend/src/assets/i18n/*.json'
jobs:
  Secrets_management:
    #needs: [DAST]
    runs-on: ubuntu-latest
    permissions: 
      contents: read 
      id-token: write 
      issues: write 
      pull-requests: write
    defaults: 
      run: 
        shell: bash 
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
      with:
        scanArguments: "--regex --entropy=False --max_depth=5000 --rules /regexes.json" # Add custom options here*
