name: TruffleHog Secret Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Get full git history

    - name: Run TruffleHog (thorough scan)
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: >-
          --no-update
          --json
          --entropy=0
          --regex
          --rules /path/to/custom/rules.json # Optional custom rules
          --since-commit HEAD~100 # Scan last 100 commits
          --branch master
          --fail
          --max-depth=10000
          --no-verification # Show unverified results too
          --no-filter
          --concurrency=10
        head: master
