name: TruffleHog Secret Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run TruffleHog
        id: scan
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: >-
            file://. 
            --json 
            --output trufflehog-results.json

      - name: Show findings (if any)
        if: always()
        run: |
          echo "=== TruffleHog Results ==="
          cat trufflehog-results.json || echo "No results file generated."

      - name: Upload TruffleHog results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json
