name: TruffleHog Secret Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # Daily scan at midnight

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full git history

    - name: Run TruffleHog Scan
      uses: trufflesecurity/trufflehog@main
      with:
        # Basic scanning (recommended for most cases)
        extra_args: >-
          --only-verified
          --json
          --fail
          git
          "file://$(pwd)"
          --since-commit HEAD~50
        head: master
        
        # Alternative more aggressive scanning (more false positives)
        # extra_args: >-
        #   --no-verification
        #   --entropy=true
        #   --regex
        #   --fail
        #   git
        #   "file://$(pwd)"
        #   --since-commit HEAD~50
